@id = 62cefbb1f4e8f428e901e18f
@host = http://localhost:3000


### Create a new trainer

POST {{host}}/trainers
Content-Type: application/json

{
    "first_name": "Ash",
    "last_name": "Ketchum",
    "class_type": "Champion"
}

### Get all trainers

GET {{host}}/trainers

### Get one trainer

GET {{host}}/trainers/{{id}}

### Patch one trainer

PATCH {{host}}/trainers/{{id}}
Content-Type: application/json

{
    "key": "last_name",
    "value": "De Lima"
}

### Update one trainer

PUT {{host}}/trainers/{{id}}
Content-Type: application/json

{
    "first_name": "Daniel",
    "last_name": "Garcia",
    "class_type": "Champion"
}

### Delete one trainer
DELETE {{host}}/trainers/{{id}}

### Delete many trainers (with a filter)
DELETE {{host}}/trainers
Content-Type: application/json

{
    "key": "last_name",
    "value": "Ketchum"
}