@id = 62d59984f160f426bf9da173
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmQ1YTY3NzNjNWViZTY3ZTYyMTljY2EiLCJpYXQiOjE2NTgxNzEyODQsImV4cCI6MTY1ODE3NDg4NH0.FUYZc3INk_UkVjMLl-6DPovp0vH1XtvGLtWsZH2QtdA

### Create a new trainer
POST {{host}}/trainers
Content-Type: application/json

{
    "first_name": "Ash",
    "last_name": "Ketchum",
    "class_type": "Champion",
    "email": "ash5@pikachu.com",
    "password": "PikaPikaKetchup"
}

### Get all trainers

GET {{host}}/trainers
Authorization: Bearer {{token}}

### Get one trainer

GET {{host}}/trainers/{{id}}

### Patch one trainer

PATCH {{host}}/trainers/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "key": "last_name",
    "value": "De Lima"
}

### Update one trainer

PUT {{host}}/trainers/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "first_name": "Daniel",
    "last_name": "Garcia",
    "class_type": "Champion"
}

### Delete one trainer
DELETE {{host}}/trainers/{{id}}
Authorization: Bearer {{token}}
### Delete many trainers (with a filter)
DELETE {{host}}/trainers
Content-Type: application/json

{
    "key": "last_name",
    "value": "Ketchum"
}